# Generated by Django 2.2 on 2019-04-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
